# Generated by Django 4.0.1 on 2022-01-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='password2',
        ),
    ]
