# Generated by Django 4.0.1 on 2022-01-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(max_length=7)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.new_user')),
            ],
        ),
    ]
