# Generated by Django 4.0.1 on 2022-01-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='balance',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='new_user',
            name='debitcard_holder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=5)),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='posts.new_user')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='posts.new_user')),
            ],
        ),
        migrations.CreateModel(
            name='Debitcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.new_user')),
            ],
        ),
    ]
